apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugo-web
  template:
    metadata:
      labels:
        app: hugo-web
    spec:
      containers:
      - name: hugo-web
        image: docker.io/library/hugo-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hugo-web-service
spec:
  selector:
    app: hugo-web
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugo-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hugo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hugo-web-service
            port:
              number: 80
